services:
  - type: web
    name: lung-disease-detection
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
